name: Sync Fork with Upstream

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork repository
        uses: actions/checkout@v3
        with:
          ref: master  # 指定要更新的分支，通常是 main

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/cche0214/CUMT.git
          git fetch upstream

      - name: Force sync from upstream to fork
        run: |
          git reset --hard upstream/master  # 强制更新到上游仓库的 main 分支
          git push origin master --force     # 强制推送到 fork 的 main 分支
